### PR TITLE
Update to trino 359

### PR DESCRIPTION
**Pull request by meneal**
There are two break changes between 356 and 359 that are handled here:

- https://github.com/trinodb/trino/pull/8042
- https://github.com/trinodb/trino/pull/7841

### CODE REVIEW

**Comment by meneal** [comment]
@shawnzhu please review.

**Comment by meneal** [comment]
Fixes #78

**Comment by meneal** [comment]
### Test Configuration

Run: `mvn clean install`

Add files to conf:
```
tree conf
conf
└── trino
    ├── catalog
    │   └── badis.properties
    ├── config.properties
    ├── jvm.config
    └── node.properties

2 directories, 4 files
```

```
cat conf/trino/config.properties
coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery-server.enabled=true
discovery.uri=http://trino-coordinator:8080
```

```
cat conf/trino/jvm.config
# from https://github.com/prestosql/presto/blob/master/docker/default/etc/jvm.config
-server
-Xmx1G
-XX:-UseBiasedLocking
-XX:+UseG1GC
-XX:G1HeapRegionSize=32M
-XX:+ExplicitGCInvokesConcurrent
-XX:+HeapDumpOnOutOfMemoryError
-XX:+UseGCOverheadLimit
-XX:+ExitOnOutOfMemoryError
-XX:ReservedCodeCacheSize=256M
-Djdk.attach.allowAttachSelf=true
-Djdk.nio.maxCachedBufferSize=2000000
```

```
cat conf/trino/node.properties
node.environment=development
node.data-dir=/data/trino
plugin.dir=/usr/lib/trino/plugin
```

```
cat docker-compose.yaml
# docker-compose.yml
version: "3.7"

services:
  trino-coordinator:
    image: trinodb/trino:359
    container_name: trino-coordinator
    volumes:
    - source: ./target/trino-db2-359
      target: /usr/lib/trino/plugin/db2
      type: bind
    - source: ./conf/trino
      target: /etc/trino
      type: bind
    ports:
      - "8080:8080"
```

The below is redacted for safety
```
cat conf/trino/catalog/badis.properties
connector.name=db2
connection-url=jdbc:db2://ip:port/database
connection-user=myuser
connection-password=mypassword
```

Setup as above and run:
- `docker compose up -d`
- `trino`
and then follow up by running 
- `show catalogs`
- `use <catalog>.<schema>`
- `select * from <some table>`

**Review by shawnzhu — APPROVED** [review]
:+1:

**Comment by shawnzhu** [comment]
@apreethi13 FYI

**Comment by meneal** [comment]
@shawnzhu I lack the permissions to merge, and likely to cut a release. Please merge and cut a release for 359 when you have a chance.

**Comment by shawnzhu** [comment]
Done

**Pull request merged**
